services:
  megalog_server:
    image: megalog_server
    container_name: megalog_server
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "production"
    networks:
      - megagera_network

networks:
  megagera_network:
    external: true

